#!/usr/bin/env python3
"""Convert Hermes Buddy concept PNGs into ESP32-friendly terminal frames.

Output format:
- 240x320 PNG previews in assets/generated/
- 4-bit indexed C header in src/generated_frames.h

Each pixel stores a palette index 0..3, two pixels per byte. The firmware can
expand this to RGB565 line buffers. Keeping the source art pre-rendered is the
right approach for anime/CRT detail on an ESP32: the MCU animates state changes,
scanlines, cursor, small offsets, and overlays instead of redrawing the character.
"""
from __future__ import annotations

import argparse
from pathlib import Path
from PIL import Image, ImageEnhance, ImageFilter

W, H = 240, 320
# Dark terminal palette, RGB. Index 0 must remain black-ish.
PAL = [
    (0, 5, 0),       # off phosphor
    (0, 42, 8),      # dim ghost
    (24, 142, 28),   # main green
    (88, 255, 83),   # hot phosphor
]


def cover_crop(im: Image.Image, w=W, h=H) -> Image.Image:
    im = im.convert("RGB")
    scale = max(w / im.width, h / im.height)
    nw, nh = int(im.width * scale + 0.5), int(im.height * scale + 0.5)
    im = im.resize((nw, nh), Image.Resampling.LANCZOS)
    left = (nw - w) // 2
    # Bias crop slightly upward: faces matter more than shoulders.
    top = max(0, min(nh - h, (nh - h) // 3))
    return im.crop((left, top, left + w, top + h))


def terminalize(src: Path, mode: str) -> Image.Image:
    im = cover_crop(Image.open(src))
    # Concepts are already green-on-black. Boost contrast and use green channel
    # as luminance so the image keeps its terminal character.
    im = ImageEnhance.Contrast(im).enhance(1.35)
    im = ImageEnhance.Sharpness(im).enhance(1.4)
    px = im.load()
    out = Image.new("P", (W, H))
    pal_flat = []
    for c in PAL:
        pal_flat.extend(c)
    pal_flat += [0, 0, 0] * (256 - len(PAL))
    out.putpalette(pal_flat)
    opx = out.load()
    for y in range(H):
        scan_dim = 0.72 if (y % 3 == 2) else (0.90 if (y % 3 == 1) else 1.0)
        for x in range(W):
            r, g, b = px[x, y]
            lum = max(g, int((r + g + b) / 3)) * scan_dim
            # Ordered dither: stable, cheap-looking CRT stipple.
            threshold_jitter = ((x * 13 + y * 7) & 15) - 7
            v = lum + threshold_jitter
            if v < 28:
                idx = 0
            elif v < 78:
                idx = 1
            elif v < 170:
                idx = 2
            else:
                idx = 3
            opx[x, y] = idx

    # Sleep should be a little dimmer; alert/happy a little brighter.
    if mode == "sleep":
        for y in range(H):
            for x in range(W):
                if opx[x, y] > 1:
                    opx[x, y] -= 1
    return out


def pack4(im: Image.Image) -> bytes:
    data = bytearray()
    pix = im.load()
    for y in range(H):
        for x in range(0, W, 2):
            data.append(((pix[x, y] & 0x0F) << 4) | (pix[x + 1, y] & 0x0F))
    return bytes(data)


def emit_header(frames: list[tuple[str, bytes]], out_path: Path) -> None:
    lines = [
        "#pragma once",
        "#include <Arduino.h>",
        "// Generated by scripts/make_terminal_frames.py. 4-bit palette, two pixels per byte.",
        f"static constexpr uint16_t HERMES_FRAME_W = {W};",
        f"static constexpr uint16_t HERMES_FRAME_H = {H};",
        "static constexpr uint16_t HERMES_TERMINAL_PALETTE[4] = { 0x0000, 0x00C0, 0x03E0, 0x57EA };",
        "",
    ]
    for name, data in frames:
        arr = f"HERMES_FRAME_{name.upper()}"
        lines.append(f"static const uint8_t {arr}[] PROGMEM = {{")
        for i in range(0, len(data), 24):
            chunk = ", ".join(f"0x{b:02X}" for b in data[i:i+24])
            lines.append(f"  {chunk},")
        lines.append("};\n")
    lines.append("struct HermesFrameDef { const char* name; const uint8_t* data; };\n")
    lines.append("static const HermesFrameDef HERMES_FRAMES[] = {")
    for name, _ in frames:
        lines.append(f"  {{\"{name}\", HERMES_FRAME_{name.upper()}}},")
    lines.append("};")
    out_path.write_text("\n".join(lines))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", type=Path, default=Path("assets/generated"))
    ap.add_argument("--header", type=Path, default=Path("src/generated_frames.h"))
    ap.add_argument("inputs", nargs="+", help="mode=path, e.g. idle=/path/img.png")
    args = ap.parse_args()
    args.outdir.mkdir(parents=True, exist_ok=True)
    frames = []
    for item in args.inputs:
        mode, path = item.split("=", 1)
        im = terminalize(Path(path), mode)
        preview = args.outdir / f"{mode}_240x320.png"
        im.convert("RGB").save(preview)
        frames.append((mode, pack4(im)))
        print(f"wrote {preview}")
    emit_header(frames, args.header)
    print(f"wrote {args.header}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
